### ISSUE TITLE
Cannot read property 'FilterType' of undefined

### ISSUE THREAD

**Issue by bobangajicsm** [rf1804/react-native-freshchat-sdk-latest#1]
```
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.2",
    "react-native-freshchat-sdk": "^2.1.0",
  },
```

and implementation

```
import { FreshchatUser, Freshchat, FreshchatConfig } from 'react-native-freshchat-sdk';


  const freshchatConfig = new FreshchatConfig('40a90971-ecde-4c43-b5f9-f53d461bab08', '47c289d2-bdc7-4f2d-8709-bb3ede7ec27b');
  Freshchat.init(freshchatConfig);
  const freshchatUser = new FreshchatUser();
  freshchatUser.firstName = "John";
  freshchatUser.lastName = "Doe";
  freshchatUser.email = "johndoe@dead.man";
  freshchatUser.phoneCountryCode = "+91";
  freshchatUser.phone = "1234234123";
  Freshchat.setUser(freshchatUser, (error) => {
    console.log(error);
  });
```

But I'm getting 

> Cannot read property 'FilterType' of undefined

 or 

> null is not an object(evaluating 'RNFreshchatSdk.Filterype'). 

Btw project is installed with npm and run react-native link command after it.

**Comment by bobangajicsm** [comment]
After adding provider tags it works now.

**Comment by agrawalsurabhi89** [comment]
I'm also facing same issue, Could you please let me know how you fixed it? @bobangajicsm

**Comment by agrawalsurabhi89** [comment]
I found the solution, we need to add freshchat SDK in iOS native side and update Library Search Path.

**Comment by linh3** [comment]
@agrawalsurabhi89 I'm also facing the same issue after upgrading the React Native version from `0.59.10` to `0.60.0`. Do you know how to properly update Library Search Path? I did add freshchat SDK in IOS, but after that keep getting a build error saying `React/RCTEventEmitter.h` file not found. Could you help me on this?

![Screen Shot 2020-10-09 at 6 04 27 PM](https://user-images.githubusercontent.com/23412215/95641910-04469100-0a5a-11eb-9396-5b660477393f.png)

**Comment by linh3** [comment]
Found the solution as following: 
Simply add `React.xcodeproj` to your Libraries folder on Xcode, and DO NOT include `libReact.a` in Link Binary With Libraries under Build Phases

<img width="1493" alt="Screen Shot 2020-10-15 at 5 51 12 PM" src="https://user-images.githubusercontent.com/23412215/96200721-7530f180-0f0f-11eb-8e6b-f5e95a2b975e.png">
